// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfQDRi5KUX_j9XxlkeuaCGNR82oPuSzTg',
    appId: '1:1054356524544:web:9583c2313391b0224412e5',
    messagingSenderId: '1054356524544',
    projectId: 'mitchchatapp-6170a',
    authDomain: 'mitchchatapp-6170a.firebaseapp.com',
    storageBucket: 'mitchchatapp-6170a.appspot.com',
    measurementId: 'G-HC9D24DD8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVnjydNkNl5_slDebkl1h8wOGr3qqH_JU',
    appId: '1:1054356524544:android:a86dc5c950f4f8094412e5',
    messagingSenderId: '1054356524544',
    projectId: 'mitchchatapp-6170a',
    storageBucket: 'mitchchatapp-6170a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtheYcF8gRLQirzqCYfMjNMFWKzB-Vg7o',
    appId: '1:1054356524544:ios:2b5f2053d182ba554412e5',
    messagingSenderId: '1054356524544',
    projectId: 'mitchchatapp-6170a',
    storageBucket: 'mitchchatapp-6170a.appspot.com',
    iosBundleId: 'com.example.mitchChatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtheYcF8gRLQirzqCYfMjNMFWKzB-Vg7o',
    appId: '1:1054356524544:ios:2b5f2053d182ba554412e5',
    messagingSenderId: '1054356524544',
    projectId: 'mitchchatapp-6170a',
    storageBucket: 'mitchchatapp-6170a.appspot.com',
    iosBundleId: 'com.example.mitchChatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfQDRi5KUX_j9XxlkeuaCGNR82oPuSzTg',
    appId: '1:1054356524544:web:175a41ecf4e28c894412e5',
    messagingSenderId: '1054356524544',
    projectId: 'mitchchatapp-6170a',
    authDomain: 'mitchchatapp-6170a.firebaseapp.com',
    storageBucket: 'mitchchatapp-6170a.appspot.com',
    measurementId: 'G-P7X68CX47E',
  );

}